[package]
name = "git-toy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5" }
libc = { version = "0.1" }
thiserror = { version = "2.0" }

[build-dependencies]
cmake = "0.1"
