[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1" }
clap = { version = "4" }
image = { version = "0.25", features = ["png"] }
rayon = { version = "1" }
